import { Inter,Domine } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Domine({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={`${inter.className} flex flex-col justify-between`}>
      <Navbar/>
     <div className="md:pt-16">{children}</div> 
      <Footer/>
      </body>
    </html>
    </ClerkProvider>
  );
}
